spring:
  application:
    name: usefuluser
  jmx:
    enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: log

  flyway:
    enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      pool-name: pool-starter
      jdbc-url: jdbc:mysql://localhost:3306/user_db
      username: apiadm
      password: folklore

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  address: 127.0.0.1
  port: 8080
  servlet:
    context-path: /api/v1